# Generated by Django 3.0.3 on 2020-02-23 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_date',
        ),
        migrations.AddField(
            model_name='startup',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
