# Generated by Django 3.0.3 on 2020-03-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200223_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
